import java.math.BigInteger; 
import java.security.MessageDigest; 
import java.security.NoSuchAlgorithmException; 

class SHA256Demo { 
    public static String getSHA(String input) 
    { 
  
        try { 
  
            // Static getInstance method is called with hashing SHA 
            MessageDigest md = MessageDigest.getInstance("SHA-256"); 
  
            // digest() method called 
            // to calculate message digest of an input 
            // and return array of byte 
            byte[] messageDigest = md.digest(input.getBytes()); 
  
            // Convert byte array into signum representation 
            BigInteger no = new BigInteger(1, messageDigest); 
  
            // Convert message digest into hex value 
            String hashtext = no.toString(16); 
  
            while (hashtext.length() < 32) { 
                hashtext = "0" + hashtext; 
            } 
  
            return hashtext; 
        } 
  
        catch (NoSuchAlgorithmException e) { 
            System.out.println("Exception thrown"
                               + " for incorrect algorithm: " + e); 
  
            return null; 
        } 
    } 
  

    public static void main(String args[]) throws NoSuchAlgorithmException 
    { 
        System.out.println("HashCode Generated by SHA-256 for:"); 
  
        String s1 = "test code"; 
        System.out.println("\n" + s1 + " : " + getSHA(s1)); 
  
        String s2 = "hello world"; 
        System.out.println("\n" + s2 + " : " + getSHA(s2)); 
    } 
} 

//test code : cf4817d9793e92a0b00b0afc241354f9a649866da1d883c604c0585ef4129b82

//hello world : b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9
