version: '2'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    image: sample-nodejs-app
    container_name: sample-nodejs-app
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app
    ports:
      - "8080:8080"   