apiVersion: v1
kind: Service
metadata:
  name: kub-service
  labels:
    name: kub-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      #protocol: TCP
  selector:
    app: node-app
  externalTrafficPolicy: Local
  type: LoadBalancer